### ISSUE TITLE
Ford_AV dataset: other_data_downloader.sh

### ISSUE THREAD

**Issue by WoojuLee24** [ShanWang-Shan/SIBCL#2]
Hello, thank you for your great work.
I'm planning to reproduce your work on the Ford-AV dataset.
But I realized that "ford_data_process/other_data_downloader.sh" only downloads the empty files. 
When I enter the file link "https://anu365-my.sharepoint.com/:u:/g/personal/u7094434_anu_edu_au/EVk_8Ah6q_hClNyEaQ7vSmYBYBysVyGZzGJmiSHMte78qg?e=qUalA1&download=1", the link has expired.

Below are the error logs:

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Downloading: 2017-08-04-V2-Log5-pcd
--2024-04-29 07:47:32--  https://anu365-my.sharepoint.com/:u:/g/personal/u7094434_anu_edu_au/EVk_8Ah6q_hClNyEaQ7vSmYBYBysVyGZzGJmiSHMte78qg?e=qUalA1&download=1
Resolving anu365-my.sharepoint.com (anu365-my.sharepoint.com)... 13.107.136.10, 13.107.138.10, 2620:1ec:8f8::10, ...
Connecting to anu365-my.sharepoint.com (anu365-my.sharepoint.com)|13.107.136.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 203118 (198K) [text/html]
Saving to: 'EVk_8Ah6q_hClNyEaQ7vSmYBYBysVyGZzGJmiSHMte78qg?e=qUalA1&download=1'

Thank you.

**Comment by ShanWang-Shan** [comment]
Thank you for your interest. I have updated the link and extended the expiration time. Could you please try downloading it again? The expiration limit is set to one month by my university server. If you encounter any issues again, please do not hesitate to contact me.

**Comment by WoojuLee24** [comment]
Thank you for your quick reply. I was able to download the files successfully, including the satellite maps. Could I ask other questions? 
1. The code 'ford_data_process/other_data_downloader.sh' provides download links only for **log3 to log 6 of 2017-08-04 and 2017-10-26**. Are the **log1 to log2 of all the dates** and **all the logs of 2017-07-24** not included in the experiments or can you provide download links?
2. I couldn't download **info files of log3, 2017-08-04** Could you upload it again?

**Comment by ShanWang-Shan** [comment]
1. For the SIBCL method, we exclusively utilize log4 in our experiments. In contrast, the PureACL method employs Log1, 3, 4 and 5. The "ALL" category in the supplementary material includes only Logs 1, 3, 4, and 5; hence, Log2 information is not provided. I have added a download link for Log1 information in 'other_data_downloader.sh'. Please pull the latest file and remove the "#" before links you want to use. Apologies, I accidentally deleted files dated 2017-07-24 and will need some time to recover this information. I have also provided the data processing source code available at "https://anu365-my.sharepoint.com/:u:/g/personal/u7094434_anu_edu_au/EfiIp8Bo5Z1MpdgV5ud0MQQBaCgv-FAxi0fSGcODUeDiUg". Please feel free to use this code to generate information, using 'info_files' as the keyword to locate related process files.
2. I believe this issue arises because you have not pulled the latest 'other_data_downloader.sh'. I have updated the link with information files for log3 dated 2017-08-04.

**Comment by WoojuLee24** [comment]
Thank you for your kind answer. I have made gps.csv, info_files, and satellite images with your help. 
But, I don't have the following LiDAR files: 
log_list = [
            '2017-07-24-V2-Log1',
            '2017-07-24-V2-Log3',
            '2017-07-24-V2-Log4',
            '2017-07-24-V2-Log5',
            '2017-08-04-V2-Log1',
            '2017-10-26-V2-Log1',
            ]

I have another question. FordAV provides the LiDAR pcd files in the bag file. But SIBCL used the 3D map of the FordAV dataset. How can I generate the 3D map pcd files? The additional source you provided doesn't seem to have the processing code for the 3D LiDAR map.

**Comment by ShanWang-Shan** [comment]
Unfortunately, we do not provide the LiDAR data directly. You can download the LiDAR data from the Ford AV dataset website. The projection from their 3D point cloud to our format is provided in the following source file:
https://github.com/ShanWang-Shan/SIBCL/blob/main/ford_data_process/project_pointcloud_to_camera.py

**Comment by WoojuLee24** [comment]
Thank you for your reply. I just wondered How SIBCL synchronized raw LiDAR and given RGB image. Now it's clear. Thank you!
